version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - laravel-network
        depends_on:
            - mysql
            - redis

    mysql:
        image: mysql:latest
        container_name: laravel-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        networks:
            - laravel-network

    redis:
        image: redis:alpine
        container_name: laravel-redis
        restart: unless-stopped
        networks:
            - laravel-network

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        networks:
            - laravel-network
        depends_on:
            - app

networks:
    laravel-network:
        driver: bridge
